stages:
  - build
job1:
  stage: build
  script:
    - echo "hello word"
    - ls -hl
    - pwd
    - cnpm install
    - npm run gulp
    - npm run test
    - ls -hl dist
    - rm -rf /opt/www/user-manager/app/*
    - cp -r dist/* /opt/www/user-manager/app/
  only:
    - test
  tags:
    - um-online-h5-app-test
